

name: CI


on:

  pull_request:
    branches: [ main, develop, tag]
    types: [closed]


  workflow_dispatch:


jobs:
 
  build:

    runs-on: ubuntu-latest

    steps:
      
      - uses: actions/checkout@v3

        
      - name: 'export TAG_TO_IMAGE main'
        if: ${{ github.ref_name == 'main' }}
        run: echo 'TAG_TO_IMAGE=latest'  >> $GITHUB_ENV
      - name: 'export TAG_TO_IMAGE develop'
        if: ${{ github.ref_name == 'develop' }}
        run: echo 'TAG_TO_IMAGE=${{ github.sha }}' >> $GITHUB_ENV
      - name: 'export TAG_TO_IMAGE tag'
        if: ${{ github.ref_name == 'tag' }}
        run: echo 'TAG_TO_IMAGE=1.0.1' >> $GITHUB_ENV
      - name: Print env.TAG_TO_IMAGE 
        run: echo ${{ env.TAG_TO_IMAGE }}
        
        
#       - name: 'docker git login'
#         run: docker login ghcr.io -u andovnar2021 --password ${{ secrets.MY_TOKEN_IMAGE_TO_GIT }}
        
      - name: 'readme'
        run: cat README.md


#       - name: "Build"
#         run: docker build . --tag ghcr.io/andovnar2021/hello-world:${{ env.TAG_TO_IMAGE }}
            
       
#       - name: "Push"
#         run: docker push ghcr.io/andovnar2021/hello-world:${{ env.TAG_TO_IMAGE }}
        
